### PR TITLE
V2 Rewrite

### PR DESCRIPTION
**Pull request by ericclemmons**
Because of bugs with the latest version of React & the upcoming changes to context, this rewrite aims to solve _complex server-side rendering **first**_, and then update for client-side usage.

### Latest Status

- [x] v2 started several months ago on an internal project.
- [x] Copy/Pasted it here under `v2`.
- [x] **Currently, porting to React v0.14**.
- [x] Re-confirm server-side rendering.
- [x] Re-confirm server & client hydration.
- [x] ~~Redux example.~~

### CODE REVIEW

**Comment by ericclemmons** [comment]
This will be done by this week.  An internal project (super complex) relies on it, and the only thing remaining is finish the client-side portion (since state changes require removing pre-loaded data).

**Comment by ericclemmons** [comment]
### React Router Demo
> v2-gif
> v2-home
> v2-stargazers

Now onto a Redux demo...

**Comment by iamdustan** [comment]
:clap: looking nice, @ericclemmons!

**Comment by ericclemmons** [comment]
What's insanely frustrating is how I just created a [React v0.13 exmaple][1] and `context.router` is lost for anything using `<Link />` (despite `<RouteHandler />` correctly trying to render the handler).
> https://github.com/ericclemmons/react-resolver/tree/34855966f46cc647ae8eb44b82dd1d626a63edec/examples/react-v0.13

```shell
$ npm install
$ npm run watch
```

Visit <http://localhost:8080/index.html> and click Submit.

Freakin' bizarre mayne.

**Comment by ericclemmons** [comment]
Just confirmed that in [Stargazers.js][1] (when I return early with `<p>Howdy!</p>` instead of the actual stargazers HTML):

```js
// NO decorators
export default class Stargazers extends React.Component {
```
> // no errors

```js
@resolve("user", ({ params }) => params.user)
export default class Stargazers extends React.Component {
```
> // no errors

```js
@resolve("users", function({ user = "ericclemmons", repo = "react-resolver" }) {
  const url = `https://api.github.com/repos/${user}/${repo}/stargazers`;

  return axios.get(url).then(({ data }) => data);
})
export default class Stargazers extends React.Component {
```
> // no errors

```js
@resolve("user", ({ params }) => params.user)
@resolve("repo", ({ params }) => params.repo)
export default class Stargazers extends React.Component {
```
> Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (resolver) while mounting Resolver (see: http://fb.me/react-context-by-parent)

And with all [3 `@resolve`s][1]:
> Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (resolver) while mounting Resolver (see: http://fb.me/react-context-by-parent)
> Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (resolver) while mounting Resolver (see: http://fb.me/react-context-by-parent)

Already, it's clear that with React v0.13 that **nested resolves lose some context** despite still _working_ for some reason.

[1]: https://github.com/ericclemmons/react-resolver/blob/34855966f46cc647ae8eb44b82dd1d626a63edec/examples/react-v0.13/src/components/Stargazers.js#L6-L8

**Comment by ericclemmons** [comment]
**MOTHER F'ING DUPLICATE REACTS!!!!!**

**Comment by ericclemmons** [comment]
**React v0.13 example is complete!**
> https://github.com/ericclemmons/react-resolver/tree/v2/examples/react-v0.13

**Pull request merged**
