### PR TITLE
Prepare for React v0.13+

### PR DESCRIPTION
**Pull request by ericclemmons**
Sebastian Markbåge wrote about Immutable Props here:
> http://facebook.github.io/react/blog/2015/02/24/streamlining-react-elements.html#immutable-props

`react-resolver` does a "double mount/render": once `componentWillMount` to initially fire off a promise for data dependencies, then for the second pass to fill in the gaps in `props`:
> https://github.com/ericclemmons/react-resolver/blob/d6d3f5236af3c81913ef8da006a3671d47c2e41f/lib/mixin.js#L24-L25

This technique is used because `this.setProps` and `this.replaceProps` can only be down on root-level components.

The question is, will this pose any issues dynamic prop resolution with 0.13?

/ping @sebmarkbage

### CODE REVIEW

**Comment by ericclemmons** [comment]
Lots of work going on here, but I'm having **major** problems resolving context issues on the client-side rendering once I introduced 2d64c6bfa1c80bcbc6d96407dcf9e60ca0efca26:

```shell
$ cd examples/stargazers/
$ npm install
$ npm start
```

> http://localhost:3000/

```
Warning: Failed Context Types: Required context `routeDepth` was not specified in `RouteHandler`.
warning.js:48Warning: Failed Context Types: Required context `router` was not specified in `RouteHandler`.
warning.js:48Warning: owner-based and parent-based contexts differ (values: `undefined` vs `1`) for key (routeDepth) while mounting RouteHandler (see: http://fb.me/react-context-by-parent)
````

So yea, this is annoying to figure out, so I'm going to call it a day or week on this until React's contexts make sense again.

**Comment by ericclemmons** [comment]
(The React maintainers who were on here for the initial discussion can safely "Unsubscribe".)

**Comment by ericclemmons** [comment]
@chadpaulson: Any idea on my context issue above?

**Comment by chadpaulson** [comment]
After reading a [related issue](https://github.com/rackt/react-router/issues/720) I stumbled upon and looking at the console output, it seems React might be loaded twice.  Will confirm soon.

**Comment by ericclemmons** [comment]
I don't think that's the issue.  If you look at the last commit, it seems the `<handler />` is losing context with the way I'm doing it.

**Comment by ericclemmons** [comment]
Actually, @chadpaulson, I'm looking into this more.  I initially ruled this out because of how similar some of the testing was previously, but I just realized that I'm not using the `dist/` version of the code in the demo!

I'll test it out and let you know!  After reading more of the comments, I definitely think you're onto something!

**Comment by ericclemmons** [comment]
@chadpaulson:  Yep!  Now to figure out the fix =/

```
React.js:109Download the React DevTools for a better development experience: http://fb.me/react-devtools
React.js:109Download the React DevTools for a better development experience: http://fb.me/react-devtools
React.js:109Download the React DevTools for a better development experience: http://fb.me/react-devtools
```

**Comment by chadpaulson** [comment]
I was able to isolate the duplicate loading by commenting out all Resolver imports.  It might be something to do with the relative inclusion of Resolver being outside of node-modules?

**Comment by ericclemmons** [comment]
I had the same issue when I switched to:

```shell
$ npm link .
$ cd examples/stargazers
$ npm link react-resolver
```

```javascript
import Resolver from "react-resolver";
```

It seems to be different versions being bundled via `react` & `react/addons`!

**Comment by ericclemmons** [comment]
Heh, just found this:
> https://www.npmjs.com/package/react-addons

**Comment by ericclemmons** [comment]
Crap.  If it's one thing, it's another.  We may have to go back to webpack because of this issue!

**Comment by chadpaulson** [comment]
Worth a try.  Wondering if the [deduplication](https://github.com/webpack/docs/wiki/optimization#deduplication) optimization would fix this.

**Comment by iamdustan** [comment]
Are you only using the `cloneWithProps` addon method? Could you switch to `React.cloneElement`? https://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html#react.cloneelement

**Comment by ericclemmons** [comment]
@iamdustan Heh, it turns out that switching from `react/addons` to plain `react` in `Context.js` revealed a whole new context issue.

I think having multiple React versions did _indeed_ cause a major problem (/ht @chadpaulson), and with some cleanup, I can take some of my other project's working context examples and apply them here.

The double-react issue was hiding, in my estimation, another context issue.

**Comment by ericclemmons** [comment]
Ok, as of f9cf0f7 I can get back to the core issues.

FYI:

- The root problem was that the example had it's own `package.json` and `node_modules`, so `import Resolver from "..."` (no matter where) would bundle this project's `react` alongside the example's `react`.
- When fixing this (by `cp -R ../../dist node_modules/react-resolver`), Browserify **still** had duplication issues.  <https://github.com/tleunen/browserify-1181> is a real bug.
- Webpack has it's own quirks, as `--hot --inline` does **not** work the same as `devServer: { hot: true, inline: true }`. O_o

So, yay. Webpack "won".

**Comment by ericclemmons** [comment]
Funny how much behavior differs.  Example showing how context is available depending on how an element is used (`ContextFixture` just displays errors if `resolver` doesn't get passed down):

```javascript
<Container element={<ContextFixture />} resolver={new Resolver()} />
```

When rendering `element`:

```javascript
return this.props.element; // FAIL
return React.addons.cloneWithProps(this.props.element); // SUCCESS
return React.cloneElement(this.props.element); // FAIL
```

Teh lame.

**Comment by spicyj** [comment]
@ericclemmons In 0.14, context provided by Container will get passed to its rendered elements – that's what the warning indicates. For 0.13, I think your best bet is to write

```
<Container elementFn={<ContextFixture />} resolver={new Resolver()} />

return this.props.elementFn();
```

which will cause the context to be passed down properly. Also please remember that context is not currently a supported or documented feature, so I appreciate your patience and understanding as we continue to iterate on the API and semantics.

**Comment by ericclemmons** [comment]
@spicyj Thanks for stopping by with tip!  These past several days have been a frustrating experience of "But it works on _their_ project!" while my migration from "mixin" to HoC was fraught with peril :D

I definitely empathize with the team refining undocumented features while we're leveraging it, quirks and all :)

**Comment by ericclemmons** [comment]
For those actually following this thread, this is why [`<FluxComponent />`][1] recommends a `render` function to ensure inner component creation/mounting/render maintains context.

[1]: http://acdlite.github.io/flummox/docs/api/fluxcomponent

**Comment by ericclemmons** [comment]
Whew boy!  d748508 was a fun one to put in.  I initially thought I'd only track resolved data via `Resolver.createContainer`, but it's much better to track each `<Container />`, since that's how context is maintained.

Plus, this is a requirement to ensure that the 1st render on the server loads all of the data, and the 2nd render uses the _cached_ data for a synchronous `React.renderToString`.

Still, there's some more to do to ensure that deeply-nested containers track & resolve as expected...

**Comment by ericclemmons** [comment]
Sweet, so this is pretty much ready for release!  A couple little nit-picks:

- Client-side rendering doesn't need to store IDs or save state for serialization. `state` _should_ be disposable within the `resolve` function.
- The only difference between server & client is that the server needs to save state between renders (as noted above).
- Maybe instead of deliberately setting `freeze` on the resolver, the `renderToString` and the `renderToStaticMarkup` can use the state object (via `new Resolver(state)`) as a reference for saving.  If it exists, save state.  If it doesn't, don't save it.
- Some of the logic (such as `getContainerState` and `getContainerId`) seem like something better suited for the `<Container />`, not the `Resolver`.
- `setState` should be chained via `.then`, not a "callback".  This is an internal library, so no need to switch styles.

**Comment by ericclemmons** [comment]
Forgot a couple things:

- Containers should support `contexts` (want to avoid `childContextTypes` and `contextTypes`) for defining things such as `{ router: React.PropTypes.function }`, which would be available for any child containers' resolve functions (e.g. `function userResolver(props, context) { ... }`)
- Relying on `new Resolver(state)` doesn't make sense, since this is how the client will bootstrap it's data.  Bootstrapping server-side data on the client _and_ indicating caching doesn't make sense.  Perhaps an internal `CachedResolver` or `IsoResolver` _is_ the correct path, since all it takes to utilize the cache is defining the `getContainerState` method.

**Comment by ericclemmons** [comment]
Alright, I'm going to merge this guy down, finish off some docs, then tag & release!

Thanks for the help from **everyone**!

Mucho <3!

**Comment by iamdustan** [comment]
:clap:

**Pull request merged**
