### PR TITLE
Resolver should remove cached data after render

### PR DESCRIPTION
**Pull request by ericclemmons**
Perhaps this only makes sense on the client (via `componentDidMount`), but the cached state should be removed so that future re-renders will re-resolve the data.

Otherwise, if you use a HoC to wrap a `Resolver.createContainer({ ... })`, the `resolve` is only ever called _once_.

### CODE REVIEW

**Comment by ericclemmons** [comment]
Remarkably easy to fix this (besides writing tests :D)!  Added lifecycle events (7697022) that use the new `resolver.clearContainerState` (787653e).

**Comment by ericclemmons** [comment]
Here's a video showing how this also fixes the issue with sibling states:
> 
stargazers

**Comment by ericclemmons** [comment]
Release `v1.1.6`!

**Comment by revolunet** [comment]
Hi, for some reason, using react-router with react-resolver, and changing sibling states, my "parent" resolvers are called each time.

```js
// Parent:
@resolve('team', function(props, context) {
  return loadTeamData()
})
// Child
@resolve('person', function(props, context) {
  return getPersonFromTeam(props.params.personId)
})
```

For example when switch from `/person/john` to `/person/eric` my team data gets reloaded... 

any idea what could cause this ?

thanks

**Comment by ericclemmons** [comment]
I believe my example is doing a "full refresh", which means everything
would get re-resolved.  Also, the resolver will fetch any data that hasn't
already come from props.  The thinking being, if `loadTeamData()` should
only happen once, this call should be memoized/cached on it's own.  (The
same way that you wouldn't fire the same GET request twice).

Another line of reasoning is if the call were instead `getSelectedUser()`.
There's no way for resolver to know if that has changed or not since the
last render.

On Tue, Jan 5, 2016 at 10:43 AM Julien Bouquillon <notifications@github.com>
wrote:

> Hi, for some reason, using react-router with react-resolver, and changing
> sibling states, my "parent" resolvers are called each time.
>
> // Parent:
> @resolve('team', function(props, context) {
>   return loadTeamData()
> })// Child
> @resolve('person', function(props, context) {
>   return getPersonFromTeam(props.params.personId)
> })
>
> For example when switch from /person/john to /person/eric my team data
> gets reloaded...
>
> any idea what could cause this ?
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericclemmons/react-resolver/pull/33#issuecomment-169056624>
> .
>
-- 
- Eric Clemmons

**Pull request merged**
