### PR TITLE
Expose and rehydrate server resolved data. Closes #22

### LINKED ISSUE #22: Bootstrap client-side data
- Need to expose `resolver.states` for serialization and output on the server.
- Client needs to bootstrap `new Resolver(window.__resolver__)` or something .

### PR DESCRIPTION
**Pull request by iamdustan**
Example WIP for #22.

### CODE REVIEW

**Comment by iamdustan** [comment]
Updated to not require changing tests for a new object return type. That said, this is subtly different in `assert.equal` uses `==` which does coerce its arguments to strings.

Also, I have a simplistic rehydration method that does immediate rerendering on the client. I suspect that this has holes, but need to try it out in a project to find them.

**Comment by iamdustan** [comment]
Alright. I now added support for resolving from a global `__resolver__` key. This implements exactly what is referenced in the primary description of #22.

The holes references previously are now patched. I’m using my branch on a few prototypes now. It resolves safely now that it is based on the component id instead of arbitrary keys. Currently avoiding all Store, flux or serialization. It’s just raw output/input.

**Comment by iamdustan** [comment]
Potential additional work would be to automatically delete the `__resolver__` key after rendering.

**Comment by gilesbradshaw** [comment]
I think I found some problems with this - please see my pull request to @iamdustan 's branch

**Comment by ericclemmons** [comment]
Is this mergeable, or do I need to combine this with https://github.com/iamdustan/react-resolver/pull/1 ?

**Comment by iamdustan** [comment]
I just merged that into my branch. Fixing the conflict now.

**Comment by iamdustan** [comment]
rebased with master. tests are passing for me locally now.

**Comment by ericclemmons** [comment]
@iamdustan I'll have to manually merge this into the v1 branch.  No problem, though!

**Comment by ericclemmons** [comment]
Just merged this into the `v1` branch as `v1.3.0`!  Thanks @iamdustan!

**Pull request closed without merging**
