### PR TITLE
[HOLD] React Router v1 messes up with missing payload

### PR DESCRIPTION
**Pull request by ericclemmons**
Hello. I'm trying to make a simple project with `react-resolver` + `react-router`. But it doesn't work. I've placed it here: https://github.com/alexbyk/react-resolver-example

Could you pls take a look... what am I missing? The simple click action causes an error (without `Resolver` works fine):
`Uncaught TypeError: Cannot read property 'firstChild' of undefined` && `TypeError: deepestAncestor is undefined`

### CODE REVIEW

**Comment by ericclemmons** [comment]
@alexbyk Can you test out this branch?  In my testing, React Router v1 works as expected, but you're my guinea pig here :)

**Comment by alexbyk** [comment]
Hey, @ericclemmons 
I can confirm that the bug is fixed in the "69-..." branch. Thanks!

**Comment by ericclemmons** [comment]
Haha!  I converted this to a PR, so I gotta open it up again :)

I'll take care of releasing this.  Thanks for confirming!

**Comment by ericclemmons** [comment]
Ok, I'm less bullish on merging this.

Going to wait for React Router v1 to be released & see if it's still an issue.

**Comment by ericclemmons** [comment]
Closing due to inactivity.

**Pull request closed without merging**
