### PR TITLE
ES6 => ES5

### PR DESCRIPTION
**Pull request by ericclemmons**
- [x] Switch to ES6 for everything
- [x] Publish to ES5
- [x] Use `peerDependencies` for `react`
- [x] ~~Use `optionalDependencies` for `react-router`~~

### CODE REVIEW

**Comment by adri** [comment]
Could `npm link` help you to test before releasing? https://docs.npmjs.com/cli/link

**Comment by adri** [comment]
Ah I see you are already doing this for the example project.

**Comment by ericclemmons** [comment]
The issue I'm having is that `npm install --production` still seems to install the `peerDependencies` as part of `react-resolver`, which I found odd...

**Comment by ericclemmons** [comment]
I'm publishing `v0.1.0` to test it out by hand :)

**Pull request merged**
