### PR TITLE
require react/lib/cloneWithProps directly instead of through addons

### PR DESCRIPTION
**Pull request by iamdustan**

### CODE REVIEW

**Comment by iamdustan** [comment]
potentially fixes #27

**Comment by ericclemmons** [comment]
Dude, thanks @iamdustan!  This works, so... I think a patch release should be fine, right?

**Comment by iamdustan** [comment]
That sounds like a patch release to me!

**Comment by BerkeleyTrue** [comment]
Reference react internal modules directly is risky as the React team has stated on multiple occasions that they will break folder directory structures without warning. Another alternative is to always pull 'react/addons' everywhere instead of just 'react'.

**Comment by iamdustan** [comment]
`react/addons` are going away, too. This is just intentionally choosing to take on the risk that they arbitrarily change modules they export.

Frankly, this is one that is likely to deprecate soon anyway and we’ll need to change to `React.cloneElement`. https://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html#react.cloneelement We can’t now for two reasons:

1. `React.cloneElement` may not preserver context (haven’t dug in, but the tests are throwing errors indicative of that when I tried itt).
2. `React.cloneElement` behaves subtly different from `cloneWithProps` and therefore could be the cause of subtle bugs. That change makes more sense at a later date bundled up with other breaking changes, IMO.

Since `react/addons` is definitely going away in the future, propagating that practice through here and therefore through all consumers of this project sounds like an anti-pattern to me.

React devs have proven to be good stewards of the project and community. Although there is no guarantee that `react/lib/cloneWithProps` will always be there, we’re just trading one risk (through indirection) for another.

**Comment by BerkeleyTrue** [comment]
Good points. I am also using cloneWithProps in one of my projects and I am facing the same dilema.

**Comment by ericclemmons** [comment]
The code behind `cloneWithProps` isn't very complex _at all_, so, worst-case scenario, we use that equivalent code until v0.14 launches with the bug fix for `React.cloneElement` to maintain context.

Until then, @BerkeleyTrue's right.  We either _always_ use `react/addons`, or `react/lib/whatever` where needed.

Personally, I feel it's safer to use the latter so that projects consuming this project don't end up with multiple copies of React via Browserify (like I had happen) by _avoiding_ references to `react/addons`.

**Comment by BerkeleyTrue** [comment]
I agree. I will probably end up using a mirror for cloneWithProps.

**Comment by ericclemmons** [comment]
v1.1.4 is out with this.  Thanks @iamdustan!

**Comment by BerkeleyTrue** [comment]
Looks like there is going to be changing addons for things are required directly (i.e. `react/addons/cloneWithProps`. That should solve this issue in a non brittle way. Maybe this will come out in next patch. https://github.com/facebook/react/issues/3780

**Comment by iamdustan** [comment]
Whoever made that change must be quite the handsome fellow.

**Pull request merged**
