### PR TITLE
upgrade to react 16

### PR DESCRIPTION
**Pull request by didi0613**

### CODE REVIEW

**Comment by ajoshi0** [comment]
@@janicetyp please can you review this and get this merged if its all good

**Comment by ajoshi0** [comment]
@jphillips-ua any luck on this please let us know

**Comment by didi0613** [comment]
Any updates on this one? Please let us know.
Thank you

**Comment by pwmckenna** [comment]
@didi0613 @ajoshi0 sorry for the delay. merged and released as 3.1.2

**Comment by didi0613** [comment]
@pwmckenna Hi, thanks for the update. After upgrading to 3.2.1, I am still getting this:
```
npm WARN react-resolver@3.1.2 requires a peer of react@^0.14.6 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN react-resolver@3.1.2 requires a peer of react-dom@^0.14.6 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.
```

Can you please help to check?

**Comment by madprog** [comment]
@didi0613 it looks like the tag was made on a wrong commit:
```
* 44a61e8 (tag: v3.1.2) 3.1.2
| * 7b1e3a7 (HEAD -> master, upstream/master, upstream/HEAD) upgrade to react 16 (#134)
|/  
* 4151b08 (tag: v3.1.1) 3.1.1
```
@pwmckenna Could you check that?

**Pull request merged**
