### PR TITLE
Replaces syntax to be compatible with vanilla node.

### PR DESCRIPTION
**Pull request by adri**
Thank you for this library. When trying it out I noticed that I couldn't use it without compiling JSX etc. 

Since I don't use webpack for the nodejs part, I replaced the JSX, destruct assignment and arrow functions.

### CODE REVIEW

**Comment by ericclemmons** [comment]
@adri Thanks for this!  I'll put this all into a release today.

I'm also determining how to make the need for `react-router` optional to avoid file-size bloat...

**Comment by jesseskinner** [comment]
+1 on the optional react-router. I'm using page.js in my current project.

**Comment by ericclemmons** [comment]
I'd be curious about seeing an example!  I assume you just do a `React.render(routeEntryPointComponent, 'app')` for each route?

But yes, `react-router` is **huge**, so I need to figure out how peer-dependencies would work...

**Comment by ericclemmons** [comment]
Same goes for `react`.  This library should be using the version your _project_ has installed.

**Comment by jesseskinner** [comment]
Right now my render function looks like this. I have a controller for each route that gets the handler and the state (handler props) and calls the render callback below. I plan to move to using react-resolver to resolve the user requirement of the app component, and ideally to replace the controllers too.

```javascript
router.render(function (handler, state) {
	var handlerElement = handler && React.createElement(handler, state);

	if (window.console && window.console.log) {
		console.log('[render]', handler && handler.displayName, state);
	}
	
	var userState = UserStore.getState();

	var app = React.createElement(Template, {
		// app state
		user: userState && userState.user

	}, handlerElement);

	React.render(app, document.getElementById('main'));
});
```

**Pull request merged**
