### PR TITLE
Fixed values and props not being passed down to the target component

### PR DESCRIPTION
**Pull request by srph**
#55 

No tests yet. Can you check, @ericclemmons?

### CODE REVIEW

**Comment by ericclemmons** [comment]
This looks good to me!

**Comment by ericclemmons** [comment]
Would it constitute a BC release?  Although this would be additive...

**Comment by srph** [comment]
Alright, gotta put up some tests when I wake up.

> BC

Not familiar with the term. Mind clarifying?

**Comment by ericclemmons** [comment]
Backwards compatibility.  You know, so we can pick the right tag:
> http://semver.org/

Frankly, I wouldn't sweat the tests.  This makes v1 more useful, but v2 is overall better (and has this functionality by design), so we can shore that up.

**Comment by srph** [comment]
Alright. But v2 isn't available by all means (npm, bower) yet, right?

**Comment by ericclemmons** [comment]
Whoops!  I should probably publish that :)  Our flagship product just got entirely redone in React (using React Resolver v2) and I haven't published it until production volume hits it on August 1st.

**Comment by srph** [comment]
Alright. I'll be waiting 'til then for v2. But I'll still insist on getting this merged for v1.

**Comment by ericclemmons** [comment]
Agreed!  I got some things to finish, but I'm 100% for keeping v1 going & not losing your hard work :)

**Comment by srph** [comment]
Ah, thanks! But I'm wondering if there were any tests written (as I didn't commit any tests, my bad).

**Comment by ericclemmons** [comment]
A test was added in v1.2.1 via @iamdustan!

**Comment by iamdustan** [comment]
Woohoo I did something useful!

**Pull request merged**
