### PR TITLE
Update dependencies and use react-dom

### PR DESCRIPTION
**Pull request by ratson**

### CODE REVIEW

**Comment by pwmckenna** [comment]
any update on this? I've tested this branch in my project (using react 14) and it works great (and eliminates warnings).

**Comment by pwmckenna** [comment]
@ratson this PR will mean dropping support for react 13 correct?

**Comment by ericclemmons** [comment]
I say go for it. :+1:

React v0.14, in my experience, should be strongly encouraged over React
v0.13 because of the fixes in how context works.

On Mon, Feb 29, 2016 at 11:21 AM Patrick Williams <notifications@github.com>
wrote:

> @ratson <https://github.com/ratson> this PR will mean dropping support
> for react 13 correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ericclemmons/react-resolver/pull/100#issuecomment-190297860>
> .
>
-- 
- Eric Clemmons

**Comment by pwmckenna** [comment]
@ericclemmons Sounds good. I'll merge and publish as a major version bump (3.0.0...breaking change without an api change) this afternoon...there are a couple dead links in the readme that I'll trim as well before the push so the npm docs get the updates.

**Pull request merged**
